/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pablocompany.proyectono1lfp.frontend.aplicacion;

import com.pablocompany.proyectono1lfp.backend.analizadorlexico.Lexema;
import com.pablocompany.proyectono1lfp.backend.analizadorlexicorecursos.AutomataPanel;
import com.pablocompany.proyectono1lfp.backend.aplicacion.ColocarFondos;
import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JScrollPane;

/**
 *
 * @author pablo
 */
public class DiagramaTransiciones extends javax.swing.JDialog {

    public DiagramaTransiciones(JDialog parent, boolean modal, Lexema lexemaRecibido) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        ColocarFondos pintarPanel = new ColocarFondos(this, this.panelPrincipal);
        pintarPanel.pintarDialog("/com/pablocompany/proyectono1/recursosapp/images/overlay2.png");

        //Clase encargada de ilustrar los movimientos del automata
        AutomataPanel automataPanel = new AutomataPanel(lexemaRecibido);

        this.lblLexema.setText("Lexema: " + lexemaRecibido.getLexema());

        JScrollPane scroll = new JScrollPane(automataPanel,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        
        this.panelTransiciones.setLayout(new BorderLayout());
        this.panelTransiciones.removeAll(); 
        this.panelTransiciones.add(scroll, BorderLayout.CENTER);
        this.panelTransiciones.revalidate();
        this.panelTransiciones.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTransicion = new javax.swing.JLabel();
        lblLexema = new javax.swing.JLabel();
        panelTransiciones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Diagrama de Transiciones");

        lblTransicion.setFont(new java.awt.Font("Liberation Serif", 1, 36)); // NOI18N
        lblTransicion.setForeground(new java.awt.Color(158, 13, 63));
        lblTransicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTransicion.setText("Diagrama de Transiciones");

        lblLexema.setFont(new java.awt.Font("Liberation Serif", 1, 30)); // NOI18N
        lblLexema.setForeground(new java.awt.Color(68, 24, 39));
        lblLexema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLexema.setText("Lexema:");

        panelTransiciones.setBackground(new java.awt.Color(255, 255, 255));
        panelTransiciones.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(50, 7, 39)));
        panelTransiciones.setAutoscrolls(true);

        javax.swing.GroupLayout panelTransicionesLayout = new javax.swing.GroupLayout(panelTransiciones);
        panelTransiciones.setLayout(panelTransicionesLayout);
        panelTransicionesLayout.setHorizontalGroup(
            panelTransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
        );
        panelTransicionesLayout.setVerticalGroup(
            panelTransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLexema, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTransicion, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelTransiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLexema)
                .addGap(18, 18, 18)
                .addComponent(panelTransiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLexema;
    private javax.swing.JLabel lblTransicion;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTransiciones;
    // End of variables declaration//GEN-END:variables
}
